version: '3.4'

services:

  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  test-db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  backend:
    container_name: backend
    image: backend-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
    command: npx nest start --watch

  minio:
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio_minio
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    volumes:
      - ./minio/data:/data